/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoologicoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class ingresarAnimal extends javax.swing.JFrame {
static ArrayList<AnimalSalvaje> agAnimal = new ArrayList();
static ArrayList<AnimalDomestico> agAnimaldos = new ArrayList();

    /**
     * Creates new form ingresarAnimal
     */
    public ingresarAnimal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        grupoSexo = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        rbtSalvaje3 = new javax.swing.JRadioButton();
        rbtDomestico3 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rbtMacho3 = new javax.swing.JRadioButton();
        rbtHembra3 = new javax.swing.JRadioButton();
        comboHabitad = new javax.swing.JComboBox<>();
        btnBuscar3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        comboPeligrosidad = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboSecLe = new javax.swing.JComboBox<>();
        comboSecNum = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("TIPO");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        grupoTipo.add(rbtSalvaje3);
        rbtSalvaje3.setText("SALVAJE");
        jPanel7.add(rbtSalvaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        grupoTipo.add(rbtDomestico3);
        rbtDomestico3.setText("DOMESTICO");
        jPanel7.add(rbtDomestico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel24.setText("RAZA");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel25.setText("SEXO");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel26.setText("HABITAD");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        grupoSexo.add(rbtMacho3);
        rbtMacho3.setText("MACHO");
        jPanel7.add(rbtMacho3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        grupoSexo.add(rbtHembra3);
        rbtHembra3.setText("HEMBRA");
        jPanel7.add(rbtHembra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        comboHabitad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACUATICO", "NOCTURNO ", "TERRESTRE", "AEREO" }));
        jPanel7.add(comboHabitad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        btnBuscar3.setText("INGRESAR");
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });
        jPanel7.add(btnBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jLabel27.setText("N. PELIGROSIDAD");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        comboPeligrosidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel7.add(comboPeligrosidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jLabel28.setText("EDAD");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));
        jPanel7.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 80, -1));

        jLabel1.setText("ID");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel7.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, -1));

        jLabel22.setText(" NOMBRE PROPIO");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel7.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, -1));
        jPanel7.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 80, -1));

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel2.setText("SECCION L.");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jLabel3.setText("SECCION #");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, -1, -1));

        comboSecLe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));
        jPanel7.add(comboSecLe, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 50, -1));

        comboSecNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel7.add(comboSecNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
Insertar();  
Limpiar();
    }//GEN-LAST:event_btnBuscar3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Animales animal = new Animales();
              animal.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JComboBox<String> comboHabitad;
    private javax.swing.JComboBox<String> comboPeligrosidad;
    private javax.swing.JComboBox<String> comboSecLe;
    private javax.swing.JComboBox<String> comboSecNum;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbtDomestico3;
    private javax.swing.JRadioButton rbtHembra3;
    private javax.swing.JRadioButton rbtMacho3;
    private javax.swing.JRadioButton rbtSalvaje3;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables

public void Insertar(){
int id, edad, peligrosidad = 0;
String nameAnimal, ownName, habitat = null;
char sex;
id = Integer.parseInt(txtId.getText());
edad = Integer.parseInt(txtEdad.getText());
nameAnimal= txtRaza.getText();
ownName = txtNombre.getText();
boolean encon= false;

switch(comboHabitad.getSelectedIndex()){
    case 0 -> habitat = "ACUATICO";
        case 1 -> habitat = "NOCTURNO";
        case 2 -> habitat = "TERRESTRE";
        case 3 -> habitat = "AEREO";
}

switch(comboSecLe.getSelectedIndex()){
        case 0 -> habitat += " A-";
        case 1 -> habitat += " B-";
        case 2 -> habitat += " C-";
        case 3 -> habitat += " D-";
        case 4 -> habitat += " E-";
        case 5 -> habitat += " F-";
        case 6 -> habitat += " G-";
}

switch(comboSecNum.getSelectedIndex()){
        case 0 -> habitat += "1";
        case 1 -> habitat += "2";
        case 2 -> habitat += "3";
        case 3 -> habitat += "4";
        case 4 -> habitat += "5";
        
}

switch(comboPeligrosidad.getSelectedIndex()){
    case 0 -> peligrosidad = 1;
        case 1 -> peligrosidad = 2;
        case 2 -> peligrosidad = 3;
        case 3 -> peligrosidad = 4;
        case 4 -> peligrosidad = 5;
}
if(rbtMacho3.isSelected()){
sex = 'M';
}else{
sex = 'F';
}
 for(AnimalSalvaje animalSal : ingresarAnimal.agAnimal){
           if(animalSal != null && animalSal.getId() == id){
                encon=true;
           }
           
       }
       for(AnimalDomestico animalDom : ingresarAnimal.agAnimaldos){
           if(animalDom != null && animalDom.getId() == id){
               encon = true;
           }
           
       }
if(encon){
JOptionPane.showMessageDialog(rootPane, "existe");
}else{
if(rbtSalvaje3.isSelected()){
    agAnimal.add( new AnimalSalvaje(peligrosidad, id, edad,nameAnimal, ownName, habitat, sex));
}else{
    
    agAnimaldos.add(new AnimalDomestico(id, edad,nameAnimal, ownName, habitat, sex));
}
}
}




 public void insertar(){
     if(agAnimal.size() ==0){
      agAnimal.add(new AnimalSalvaje(1, 123, 12,"oso", "polar", "TERRESTRE F-5", 'M'));
      agAnimal.add(new AnimalSalvaje(1, 12345, 7,"leon", "lion", "TERRESTRE A-3", 'F'));
     }
     if(agAnimaldos.size() ==0){
    agAnimaldos.add(new AnimalDomestico(1234, 4,"mecho", "perro", "TERRESTRE G-4", 'M'));
    agAnimaldos.add(new AnimalDomestico(123456, 124,"gata", "gato", "TERRESTRE G-3", 'F'));
     }
    }

public void Limpiar(){
txtId.setText("");
txtNombre.setText("");
txtRaza.setText("");
txtEdad.setText("");

}
}
